version: '3'

services:
  booking-service:
    build: ./server
    ports:
      - "8081:8081"

  booking-service2:
    build: ./server
    ports:
      - "8082:8081"

  booking-service-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: